const wait = (duration) => {
    return new Promise(resolve => setTimeout(resolve, duration * 1000));
}

const play = async () => {
    const backgroundVideo = document.getElementById('background-video');
    document.getElementById('bgm').removeEventListener('play', play);
    await wait(0.2);

    const 이것은 = document.getElementById('1');
    gsap.set(이것은, { className: "active" });
    await wait(0.1);
    await gsap.to(이것은, { duration: 0.15, fontSize: '3rem'});
    await gsap.to(이것은, { duration: 0.6, innerText: '바로' });
    await gsap.to(이것은, { duration: 0.1, x: '-5rem', opacity: 0 });
    gsap.set(이것은, { className: "" });

    const 애플의 = document.getElementById('2');
    gsap.set(애플의, { className: "active" });
    await wait(0.01);
    애플의.style.opacity = 1;
    애플의.style.transform = '';
    await gsap.to(애플의, { duration: 0.3, innerText: '애플의 거대한' });
    await gsap.to(애플의, { duration: 0.25, innerText: '애플의 거대한 출시' });
    await gsap.to(애플의, { duration: 0.25, innerText: '        거대한 출시' });
    await gsap.to(애플의, { duration: 0.25, innerText: '                    출시' });
    await gsap.to(애플의, { duration: 0.1, innerText: '출시' });
    await gsap.to(애플의, { duration: 0.1, innerText: '오직' });
    애플의.innerText = '107';
    await gsap.from(애플의, {
        innerText: 0,
        duration: 0.4,
        snap: { innerText: 1 },
        stagger: {
            each: 1.0
        },
        onUpdate : function() {
            this.targets()[0].innerText = `오직 ${this.targets()[0].innerText}`
          }
    });
    await wait(0.5);
    애플의.innerText = '오직 107 초';
    await wait(0.45);
    애플의.innerText = '오직 107 초 안에';
    애플의.style.transition = '';
    await wait(0.4);

    const readyDiv = document.getElementById('ready?');
    const [준, 비, 되, 셨, 나, 요, 물음표] = document.getElementsByClassName('ready');
    gsap.set(애플의, { className: "" });
    gsap.set(readyDiv, { className: "active-flex" });
    gsap.set(비, { opacity: 1 });
    gsap.set(되, { opacity: 1 });
    await wait(0.03);
    gsap.set(나, { opacity: 1 });
    await wait(0.04);
    gsap.set(준, { opacity: 1 });
    await wait(0.05);
    gsap.set(셨, { opacity: 1 });
    await wait(0.06);
    gsap.set(물음표, { opacity: 1 });
    gsap.set(요, { opacity: 1 });
    await wait(0.15);
    gsap.to(readyDiv, { duration: 0.2, scale: 0.7 });
    await wait(0.2);
    gsap.set(readyDiv, { className: "" });
    await wait(0.1);

    const 눈을 = document.getElementById('3');
    gsap.set(눈을, { className: "active" });
    await wait(0.25);
    눈을.innerText = '깜빡이지'
    await wait(0.25);
    눈을.innerText = '말고'
    await wait(0.25);
    눈을.innerText = '바라보세요'
    await wait(0.25);
    눈을.innerText = '깜빡'
    눈을.style.fontSize = '15rem';
    await wait(0.1);
    const popup1 = document.getElementById('popup-1');
    gsap.set(눈을, { className: "" });
    gsap.set(popup1, { className: "active-flex" });
    await wait(0.1);
    gsap.set(popup1, { className: "" });
    gsap.set(눈을, { className: "active" });
    눈을.style.fontSize = '8rem';
    await wait(0.1);
    눈을.style.scale = 0;
    await wait(0.1);
    gsap.set(눈을, { className: "" });
    await wait(0.25);
    const countdown = document.getElementById('countdown');
    gsap.set(countdown, { className: "active" });
    await wait(0.01);
    document.body.style.backgroundColor = 'white';
    countdown.style.color = 'black';
    countdown.style.fontSize = '2rem';
    await wait(0.45);
    countdown.style.transition = '';
    countdown.style.fontSize = '200rem';
    await wait(0.01);
    countdown.innerText = 2;
    countdown.style.transition = 'font-size 400ms';
    document.body.style.backgroundColor = 'black';
    countdown.style.color = 'white';
    countdown.style.fontSize = '2rem';
    await wait(0.45);
    countdown.style.transition = '';
    countdown.style.fontSize = '200rem';
    await wait(0.01);
    countdown.innerText = 1;
    countdown.style.transition = 'font-size 400ms';
    document.body.style.backgroundColor = 'white';
    countdown.style.color = 'black';
    countdown.style.fontSize = '2rem';
    await wait(0.45);
    document.body.style.backgroundColor = 'black'
    countdown.classList.remove('active')
    await wait(0.2);
    const alabama = document.getElementById('alabama');
    gsap.set(alabama, { className: "active" });
    await gsap.to(alabama, { duration: 0.3, fontSize: '4rem' });
    await gsap.to(alabama, { duration: 0.2, innerText: '팀 쿡' });
    await gsap.to(alabama, { duration: 0.2, innerText: '퍼렐' });
    await gsap.to(alabama, { duration: 0.2, innerText: '그리고' });
    await gsap.to(alabama, { duration: 0.2, innerText: '제임스 코든이' });
    await gsap.to(alabama, { duration: 0.2, innerText: '카풀로' });
    await gsap.to(alabama, { duration: 0.2, innerText: '강당을' });
    await gsap.to(alabama, { duration: 0.2, innerText: '향해' });
    await gsap.to(alabama, { duration: 0.475, innerText: '갑니다' });
    gsap.set(alabama, { className: "" });
    backgroundVideo.src = '/alabama.mp4';
    gsap.set(backgroundVideo, { className: "active" });
    backgroundVideo.play();
    await wait(2.4);
    gsap.set(backgroundVideo, { className: "" });
    gsap.set(alabama, { className: "active" });
    await gsap.to(alabama, { duration: 0.2, innerText: '팀이' });
    await gsap.to(alabama, { duration: 0.2, innerText: '무대' });
    await gsap.to(alabama, { duration: 0.2, innerText: '위로' });
    await gsap.to(alabama, { duration: 0.2, innerText: '걸어' });
    await gsap.to(alabama, { duration: 0.2, innerText: '올라갑니다' });
    gsap.set(alabama, { className: "" });
    gsap.set(backgroundVideo, { className: "active" });
    backgroundVideo.src = '/stage.mp4';
    backgroundVideo.play();
    await wait(0.5);
    gsap.set(backgroundVideo, { className: "" });
    gsap.set(alabama, { className: "active" });
    await gsap.to(alabama, { duration: 0.2, innerText: '그가' });
    await gsap.to(alabama, { duration: 0.2, innerText: '말합니다' });
    await gsap.to(alabama, { duration: 0.1, innerText: 'Bonjour' });
    await gsap.to(alabama, { duration: 0.1, innerText: 'Привет' });
    await gsap.to(alabama, { duration: 0.1, innerText: 'Hello!' });
    await gsap.to(alabama, { duration: 0.1, innerText: 'どうぞ' });
    await gsap.to(alabama, { duration: 0.1, innerText: 'Ciao!' });
    await gsap.to(alabama, { duration: 0.1, innerText: 'Hola' });
    await gsap.to(alabama, { duration: 0.1, innerText: 'Olá' });
    gsap.set(alabama, { className: "" });
    document.body.style.backgroundColor = 'white';
    const hello = document.getElementById('hello');
    gsap.set(hello, { className: "active" });
    await wait(0.1);
    await gsap.to(hello, { duration: 0.05, transform: 'translateX(-3rem)' });
    await wait(0.1);
    hello.style.transform = '';
    hello.style.fontSize = '10rem';
    hello.style.transition = '';
    await wait(0.1);
    hello.innerText = '모두들 안녕하세요.';
    hello.style.maxWidth = '0%';
    await wait(0.01);
    document.body.style.transition = 'background-color 300ms';
    hello.style.transition = 'max-width 500ms ease-out';
    hello.style.maxWidth = '100%';
    await wait(0.45);
    hello.style.overflow = '';
    hello.style.maxWidth = '';
    gsap.to(hello, { duration: 0.6, ease: 'CustomEase.create("custom", "M0,0 C0.516,0.296 0.421,0.931 0.542,0.985 0.679,1.046 0.813,1.025 1,1.025 ")', scale: 10 });
    await wait(0.25);
    document.body.style.backgroundColor = 'black';
    await wait(0.1);
    gsap.set(hello, { className: "" });
    document.body.style.transition = '';
    const introduce = document.getElementById('introduce');
    gsap.set(introduce, { className: "active" });
    await wait(0.1);
    introduce.style.fontSize = '4rem';
    await wait(0.2);
    introduce.innerText = '여러분들께';
    await wait(0.5);
    introduce.innerText = '보여';
    await wait(0.4);
    introduce.innerText = '보여드릴';
    await wait(0.325);
    introduce.innerText = '보여드릴 것이';
    await wait(0.325);
    introduce.innerText = '있습니다';
    await wait(0.2);
    introduce.style.opacity = 0;
    wait(1.5).then(() => {
        gsap.set(introduce, { className: "" });
    });
    gsap.set(backgroundVideo, { className: "active" });
    backgroundVideo.src = '/iphone 7 first show.mp4';
    backgroundVideo.play();
    wait(5.6).then(() => {
        backgroundVideo.classList.remove('active');
    });
    await wait(3);
    const desc1 = document.getElementById('desc-1');
    const desc2 = document.getElementById('desc-2');
    gsap.set(desc1, { className: "active" });
    await wait(0.01);
    desc1.style.opacity = 1;
    await wait(1.5);
    desc1.style.opacity = 0;
    desc1.style.transform = 'translateX(-4rem)';
    await wait(0.01);
    gsap.set(desc2, { className: "active" });
    await wait(0.01);
    desc2.style.opacity = 1;
    desc2.style.transform = '';
    wait(0.25).then(() => {
        gsap.set(desc1, { className: "" });
    });
    await wait(1);
    desc2.style.opacity = 0;
    gsap.set(desc2, { className: "" });
    const bigSeven = document.getElementById('big-seven');
    gsap.set(bigSeven, { className: "active" });
    document.body.style.backgroundColor = 'white';
    await wait(0.25);
    gsap.set(bigSeven, { className: "" });
    document.body.style.backgroundColor = 'black';
    const sevenSpelling = document.getElementById('seven-spelling');
    gsap.set(sevenSpelling, { className: "active-flex" });
    await wait(0.25);
    const [sp1, sp2, sp3, sp4, sp5, sp6, sp7] = sevenSpelling.getElementsByTagName('span');
    sp2.innerText = 'i';
    sp5.innerText = 't';
    sp7.style.scale = 0;
    sp7.style.display = 'none';
    await wait(0.25);
    sp4.innerText = 'p';
    sp2.style.scale = 0;
    sp2.style.display = 'none';
    sp6.style.scale = 0;
    sp6.style.display = 'none';
    await wait(0.25);
    sp5.style.scale = 0;
    sp5.style.display = 'none';
    sp4.style.scale = 0;
    sp4.style.display = 'none';
    sp1.innerText = '일';
    sp3.innerText = '곱';
    await wait(0.25);
    gsap.set(sevenSpelling, { className: "" });
    document.body.style.backgroundColor = 'white';
    const sevenDesc1 = document.getElementById('seven-desc-1');
    const [sd1_1, sd1_2] = sevenDesc1.getElementsByTagName('span');
    const sevenDesc2 = document.getElementById('seven-desc-2');
    const [sd2_1, sd2_2, sd2_3] = sevenDesc2.getElementsByTagName('span');
    gsap.set(sevenDesc1, { className: "active-flex" });
    sd1_1.style.opacity = 1;
    await wait(0.25);
    sd1_2.style.opacity = 1;
    await wait(0.25);
    gsap.set(sevenDesc1, { className: "" });
    gsap.set(sevenDesc2, { className: "active-flex" });
    sd2_1.style.opacity = 1;
    await wait(0.25);
    sd2_2.style.opacity = 1;
    await wait(0.25);
    sd2_3.style.opacity = 1;
    await wait(0.25);
    sevenDesc2.style.transform = 'scale(0.67)';
    await wait(0.25);
    gsap.set(sevenDesc2, { className: "" });
    const sevenDesc3 = document.getElementById('seven-desc-3');
    document.body.style.backgroundColor = 'black';
    gsap.set(sevenDesc3, { className: "active" });
    await wait(0.25);
    sevenDesc3.innerText = '블랙 블랙.';
    await wait(0.25);
    gsap.set(sevenDesc3, { className: "" });
    gsap.set(backgroundVideo, { className: "active" });
    backgroundVideo.src = '/iphone 7 2.mp4';
    backgroundVideo.play();
    await wait(0.3);
    gsap.set(backgroundVideo, { className: "" });
    const sevenDesc4 = document.getElementById('seven-desc-4');
    const [sd4_1, sd4_2, sd4_3] = sevenDesc4.getElementsByTagName('span');
    gsap.set(sevenDesc4, { className: "active-flex" });
    sd4_1.style.opacity = 1;
    await wait(0.125);
    sd4_2.style.opacity = 1;
    await wait(0.125);
    sd4_1.style.opacity = 0;
    await wait(0.125);
    sd4_3.style.opacity = 1;
    await wait(0.125);
    sd4_2.style.opacity = 0;
    await wait(0.125);
    sd4_3.style.opacity = 0;
    await wait(0.125);
    gsap.set(sevenDesc4, { className: "" });
    const sevenDesc5 = document.getElementById('seven-desc-5');
    const [sd5_1, sd5_2] = sevenDesc5.getElementsByTagName('span');
    gsap.set(sevenDesc5, { className: "active-flex" });
    sd5_1.style.opacity = 1;
    await wait(0.125);
    sd5_2.style.opacity = 1;
    await wait(0.125);
    gsap.set(sevenDesc5, { className: "" });
    gsap.set(backgroundVideo, { className: "active" });
    backgroundVideo.src = '/iphone 7 3.mp4';
    backgroundVideo.play();
    await wait(0.3);
    gsap.set(backgroundVideo, { className: "" });
    const sevenDesc6 = document.getElementById('seven-desc-6');
    const [sd6_1, sd6_2, sd6_3] = sevenDesc6.getElementsByTagName('span');
    gsap.set(sevenDesc6, { className: "active-flex" });
    sd6_1.style.opacity = 1;
    await wait(0.125);
    sd6_2.style.opacity = 1;
    await wait(0.125);
    sd6_3.style.opacity = 1;
    await wait(0.125);
    gsap.set(sevenDesc6, { className: "" });
    const sevenDesc7 = document.getElementById('seven-desc-7');
    const [sd7_1, sd7_2] = sevenDesc7.getElementsByTagName('span');
    const [sd7_2_1, sd7_2_2] = sd7_2.getElementsByTagName('span');
    gsap.set(sevenDesc7, { className: "active-flex" });
    sd7_1.style.opacity = 1;
    sd7_2.style.maxWidth = '0%';
    await wait(0.125);
    sd7_2.style.display = 'flex';
    await wait(0.05);
    sd7_2.style.maxWidth = '100%';
    await wait(0.6);
    sd7_1.style.opacity = 0;
    sd7_2_2.style.opacity = 0;
    gsap.to(sd7_2_1, { duration: 0.4, opacity: 0 })
    wait(0.4).then(() => {
        gsap.set(sevenDesc7, { className: "" });
    });

    gsap.set(backgroundVideo, { className: "active" });
    backgroundVideo.src = '/iphone 7 4.mp4';
    backgroundVideo.play();
    await wait(1.4);
    gsap.set(backgroundVideo, { className: "" });

}

document.addEventListener('DOMContentLoaded', () => {
    document.getElementById('bgm').addEventListener('play', play);
    setTimeout(() => { document.getElementById('bgm').play(); }, 500)
});